package ai.rever.boss.plugin.api

/**
 * Least-privilege secret access for plugin and tool code.
 *
 * Unlike [SecretDataProvider], this provider is bound by the host to the calling execution
 * principal. The principal is intentionally not an argument to any method: accepting a plugin id,
 * tool name, or MCP name from the caller would let untrusted code impersonate another principal.
 *
 * The host and backing store enforce these rules at every operation:
 *
 * - a secret created through this provider is owned by the bound principal;
 * - reads and searches return only secrets owned by that principal or explicitly granted to it by
 *   a human;
 * - legacy/human secrets with no execution-principal owner are never returned unless a human has
 *   explicitly granted that particular secret to the principal;
 * - update and delete apply only to secrets owned by the bound principal. A grant permits use, not
 *   mutation or onward sharing;
 * - revoking a grant takes effect on the next operation. Implementations must not expose a
 *   long-lived plaintext cache that outlives authorization.
 *
 * A plugin receives a plugin-bound instance from [PluginContext.secretAccessProvider]. When code
 * runs as an MCP tool or another narrower tool identity, the host must rebind the provider to that
 * invocation identity; a tool must not inherit its containing plugin's broader access merely
 * because its handler is implemented by that plugin.
 *
 * This interface is intentionally separate from the human vault-management surface. UI code such
 * as Secret Manager and the trusted browser credential channel continue to use host-authorized
 * human workflows; agents, plugins, tools, and MCP calls use this scoped surface.
 */
@HostImplemented
interface SecretAccessProvider {
    /**
     * List non-secret metadata visible to the bound principal.
     *
     * Plaintext values require an explicit [getSecret] call. Ownerless human secrets are absent
     * unless explicitly granted to this principal.
     */
    suspend fun listSecrets(limit: Int = 50, offset: Int = 0): Result<PaginatedAccessibleSecrets>

    /** Search only within the same principal-scoped view as [listSecrets]. */
    suspend fun searchSecrets(
        query: String,
        limit: Int = 50,
        offset: Int = 0,
    ): Result<PaginatedAccessibleSecrets>

    /**
     * Resolve one secret by id, returning null when it does not exist *or is not authorized*.
     *
     * Keeping those cases indistinguishable prevents callers from probing ids to discover vault
     * contents they cannot read.
     */
    suspend fun getSecret(secretId: String): Result<SecretEntryData?>

    /**
     * Create a secret owned by the provider's host-bound execution principal.
     *
     * The returned id is generated by the trusted backing store. Implementations must never infer
     * ownership from request fields, tags, or notes.
     */
    suspend fun createSecret(request: CreateSecretRequestData): Result<String>

    /** Update a secret only when the bound principal owns it. Grants do not permit mutation. */
    suspend fun updateOwnedSecret(request: UpdateSecretRequestData): Result<Unit>

    /** Delete a secret only when the bound principal owns it. Grants do not permit deletion. */
    suspend fun deleteOwnedSecret(secretId: String): Result<Unit>
}

/** A page of non-secret records available through [SecretAccessProvider]. */
data class PaginatedAccessibleSecrets(
    val data: List<AccessibleSecretMetadata>,
    val hasMore: Boolean,
)

/**
 * Non-secret metadata for an execution-principal-visible secret.
 *
 * [accessLevel] is an open string so the backing policy can grow without changing this type. The
 * initial values are `owner` (the bound principal created it) and `use` (a human granted use).
 * Notes, passwords, recovery codes, and TOTP seeds are intentionally absent.
 */
data class AccessibleSecretMetadata(
    val id: String,
    val website: String,
    val username: String,
    val expirationDate: String? = null,
    val tags: List<String> = emptyList(),
    val createdAt: String,
    val updatedAt: String,
    val accessLevel: String,
)

/**
 * Human-only management of execution-principal grants.
 *
 * The host exposes this surface only to the trusted Secret Manager UI. It must never be available
 * to ordinary plugins, agents, tools, or MCP handlers: those callers use [SecretAccessProvider]
 * and cannot grant themselves access or enumerate other principals.
 */
@HostImplemented
interface SecretGrantManager {
    /** Installed principals a human may explicitly grant a secret to. Contains no secret data. */
    suspend fun listPrincipals(): Result<List<SecretPrincipalData>>

    /** Grants currently attached to [secretId], visible only when the human may manage it. */
    suspend fun listGrants(secretId: String): Result<List<SecretPrincipalGrantData>>

    /** Grant use of one secret to one host-known principal after an explicit human action. */
    suspend fun grantSecret(
        secretId: String,
        principalType: String,
        principalId: String,
    ): Result<Unit>

    /** Revoke one explicit execution-principal grant. */
    suspend fun revokeSecret(
        secretId: String,
        principalType: String,
        principalId: String,
    ): Result<Unit>
}

/**
 * A host-known plugin or tool identity shown in the human grant picker.
 *
 * [principalType] is an open string. Initial values are `plugin` and `mcp_tool`.
 */
data class SecretPrincipalData(
    val principalType: String,
    val principalId: String,
    val displayName: String,
    val description: String? = null,
)

/** One persisted human grant. No plaintext secret value is included. */
data class SecretPrincipalGrantData(
    val principalType: String,
    val principalId: String,
    val grantedAt: String,
    val grantedByUserId: String,
)
